### Input
# input text prompt (default to None, can be input in GUI too)
prompt:
# estimated elevation angle for input image 
elevation: 0
# reference image resolution
ref_size: 256



### Training
# guidance loss weights (0 to disable)
lambda_sd: 0
lambda_zero123: 0
lambda_controlnet: 1


# training camera radius
radius: 2.2
# training camera fovy
fovy: 49.1 # align with zero123 rendering setting (ref: https://github.com/cvlab-columbia/zero123/blob/main/objaverse-rendering/scripts/blender_script.py#L61
# checkpoint to load for stage 1 (should be a ply file)
load:
# whether allow geom training in stage 2
train_geo: False
# prob to invert background color during training (0 = always black, 1 = always white)
invert_bg_prob: 0.5


# legacy
H: 800
W: 800

### CD Loss
lambda_cd_init: 0
lambda_cd_end: 1000000    # 1e6
lambda_cd_end_step: 2000


